### PR TITLE
Allow passing options to server when creating the connection.

### PR DESCRIPTION
**Pull request by amit-gshe**

### CODE REVIEW

**Comment by seiyria** [comment]
* what purpose does this actually serve? what options are you passing in here that you wouldn't pass in when joining etc?
* why is the .d.ts entirely changed when only one line changed? might want to make sure your diff is being reflected accurately
* `    protected connect(colyseusid: string,options: any = {}) {` you might want to add a space after the comma there (for lint purposes)

**Comment by amit-gshe** [comment]
@seiyria , 
>     * what purpose does this actually serve? what options are you passing in here that you wouldn't pass in when joining etc?
The  server has an `verifyClient` option, so we can verify the client when it connected to server and before they trying joining the room. Now we have no way to add some request parameters such as user token when the first connection to the server. By the way, the first connection to the server can be used as a main connection and we can use to communicate with client (by some other `Protocol`). Yes we can add them to a chat room but this way needs to add an another expensive connection to the chat room.

>     * why is the .d.ts entirely changed when only one line changed? might want to make sure your diff is being reflected accurately
> 
>     * `    protected connect(colyseusid: string,options: any = {}) {` you might want to add a space after the comma there (for lint purposes)
Sorry for these two mistakes and should I give an another pull request?

**Comment by seiyria** [comment]
You should just commit to the branch for this pr to update it.

As for passing options, is it not sufficient to pass them in client.join()?

**Comment by amit-gshe** [comment]
In some use cases, such as that we need to maintain a message channel to the verified user out of the room or the user may not join a room immediately, the options pass by `client.join()` is not sufficient.

**Comment by amit-gshe** [comment]
@seiyria 
>     * why is the .d.ts entirely changed when only one line changed? might want to make sure your diff is being reflected accurately
The line ending of `colyseus.d.ts` is `CRLF` and other files in this repository are `LF`. Should I change it to `CRLF` back?

**Comment by seiyria** [comment]
Yes, you should strive to make your diff as minimal as possible to ensure ease of review.

**Comment by endel** [comment]
Thanks for your pull-request @amit-gshe! It does make sense!
And thanks a lot for taking your time to review this @seiyria ❤️

**Pull request merged**
